framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'
            telegram: '%env(TELEGRAM_DSN)%'
            discord: '%env(DISCORD_DSN)%'
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'

when@test:
    framework:
        notifier:
            chatter_transports:
                slack: 'null://null'
                telegram: 'null://null'
                discord: 'null://null'
            texter_transports:
                twilio: 'null://null'
