services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Support\MockResponseFactory:
        autoconfigure: false

    App\Service\WorkflowConfigLoader:
        public: true
        arguments:
            $workflowsDirectory: '%kernel.project_dir%/config/workflows'

    App\Service\WorkflowExecutor:
        public: true
